MOVIE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movapp/urls.py
from django.urls import path
from . import views

app_name = 'movapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('create_movie', views.create_movie, name='create_movie'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('register/', views.register, name='signup'),
    path('(?P<movie_id>[0-9]+)/delete_movie/', views.delete_movie, name='delete_movie'),




]

movapp/models.py
from unittest.test.testmock.testpatch import Foo

from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
from django.contrib.contenttypes.fields import GenericRelation


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50)


    def get_absolute_url(self):
        return reverse('moviesapp:index')


class Movie(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    genre = models.CharField(max_length=50)
    year = models.IntegerField()
    cover = models.ImageField()
    is_new = models.BooleanField()
    url = models.URLField()
    video = models.FileField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField(blank=True, default=1)

    def __str__(self):
        return self.title


class Comment(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()

    def __str__(self):
        return self.comment


# Create your models here.

movapp/forms.py
from django import forms
from . models import Movie, User


class MovieForm(forms.ModelForm):

    class Meta:
        model = Movie
        fields = '__all__'


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

movapp/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Movie, Category
from . forms import MovieForm, UserForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):
    movies = Movie.objects.all()
    return render(request, 'movapp/index.html', {'movies': movies})


def detail(request, movie_id):
    movies = get_object_or_404(Movie, pk=movie_id)
    return render(request, 'movapp/index.html', {'movies': movies})


@login_required(login_url='movapp:login_user')
def create_movie(request):
    form = MovieForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        movie = form.save(commit=False)
        movie.cover = request.FILES['cover']
        movie.user = request.user
        movie.save()
        movie = Movie.objects.all()
        context = {'movie':movie,
                   'message':'Movie Created!'
                   }
        return render(request, 'movapp/index.html',context)
    form = MovieForm()

    return render(request, 'movapp/create_movie.html',
                  {'form': form})

def delete_movie(request, movie_id):
    movie = Movie.objects.get(pk=movie_id)
    movie.delete()
    movie = Movie.objects.all()
    return render(request, 'movapp/index.html', {'movie':movie})



def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                movies = Movie.objects.filter(user=request.user)
                return render(request, 'movapp:index.html', {'movies': movies})
    return render(request, 'movapp/login.html')

def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        context = {'form':form,
                   'message':'Registered successfully!'
                   }
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                movies = Movie.objects.filter(user=request.user)
                return render(request, 'movapp/index.html', {'movies':movies})
    return render(request, 'movapp/register.html', {'form': form})



def logout_user(request):
    logout(request)
    return redirect('movapp:login_user')

movapp/templates/movapp/base.html
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">

    <title></title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    </head>

<body>

<nav class="navbar navbar-inverse">

    <div class="container-fluid">



        <!-- Header -->

        <div class="navbar-header">

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>

            </button>

            <a class="navbar-brand" href="">movapp</a>

        </div>



        <!-- Items -->

        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav">

                <li> <a href=""><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Home</a></li>


            </ul>

            <ul class="nav navbar-nav">
                <li><a href=""><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>LATEST TRAILERS </a> </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="">

                <div class="form-group">

                    <input type="text" class="form-control" name="q" value="">

                </div>

                <button type="submit" class="btn btn-default">Search</button>

            </form>

            <ul class="nav navbar-nav navbar-right">

                <li>

                    <a href="{% url 'movapp:create_movie' %}">

                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Movie

                    </a>

                </li>

                {% if user.is_authenticated %}

                <li>

                    <a href="{% url 'movapp:logout_user' %}">

                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Log Out

                    </a>

                </li>

                {% else %}

                <li>

                    <a href="{% url 'movapp:login_user' %}">

                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; LogIn

                    </a>

                </li>

                {% endif %}



            </ul>

        </div>



    </div>

</nav>
{% block content %}


{% endblock %}


</body>

</html>

movapp/templates/movapp/create_movie.html
{% extends 'movapp/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="text-primary">Add Movie</h3>
                </div>
                <div class="panel-body">
                    {% if message %}
                    <p class="text-danger"><b>{{ message }}</b></p>
                       {% endif %}
                    <form method="post" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}

                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

movapp/templates/movapp/form_template.html
{% for field in form %}

    <div class="form-group">

        <div class="col-sm-offset-2 col-sm-10">

            <span class="text-danger small">{{ field.errors }}</span>

        </div>

        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>

        <div class="col-sm-10">{{ field }}</div>

    </div>

{% endfor %}

movapp/templates/movapp/index.html
{% extends 'movapp/base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <h3 class="text-center text-primary">
            BURNITY
        </h3>
        {% if movies %}
            {% for movie in movies %}
        <div class="col-sm-3">
            <div class="thumbnail">
                <a href="">
                    <video width="200" height="250" controls>
                        <source src="{{ movie.video.url }}">
                    </video>
                </a>
                <div class="caption">
                    <h5>{{ movie.title  }}</h5>
                    <form method="post" action="">
                        {% csrf_token %}
                        <input type="hidden" name="movie.id" value="{{ movie.id }}">
                        <a href="{% url 'movapp:delete_movie' movie.id %}">
                         <span class="glyphicon glyphicon-trash"></span>
                        </a>
                    </form>
                </div>
            </div>
         </div>
           {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}

movapp/templates/movapp/login.html
{% extends 'movapp/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container-fluid">
    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3>Login</h3>
                </div>

                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label">Username:</label>
                            <input type="text" class="form-control" name="username">
                        </div>

                        <div class="form-group">
                            <label class="control-label">Password:</label>
                            <input type="password" class="form-control" name="password">
                        </div>


                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Login</button>
                        </div>

                        <div>
                            <p> Not Registered? <a href="{% url 'movapp:signup' %}">Register</a></p>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
    </div>
{% endblock %}

movapp/templates/movapp/register.html
{% extends 'movapp/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="text-primary">Sign Up</h3>
                </div>
                <div class="panel-body">
                    <form method="post" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}

                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                        <p>Already Registered? <a href="{% url 'movapp:login_user' %}">Login</a></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}